# locale
export LANG=en_US.UTF-8
# charcode
export KCODE=u
# Editor
export EDITOR="vim"
# reporttime
export REPORTTIME=5
# path
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.gem/ruby/2.1.0/bin:$PATH"
export PATH="$HOME/.cabal/bin:$PATH"
