#!/bin/zsh

touchpad=`cat /sys/devices/platform/sony-laptop/touchpad`
if [ "$touchpad" -eq 0 ]
then
  echo 1 | tee /sys/devices/platform/sony-laptop/touchpad
else
  echo 0 | tee /sys/devices/platform/sony-laptop/touchpad
fi
